### ISSUE TITLE
Doesn't seem to work for me?

### ISSUE THREAD

**Issue by Rykimaruh** [Eternita-S/AntiAfkKick#10]
I'm not entirely sure when this left movement key press happens, is it when I have the game minimized, when I have the game window open?

**Comment by patrat46** [comment]
Hello~~
What version are you currently running? The Standalone, or Act or the other one? 

The program looks for idle time based of the last keystone in the active window.
If the window is not active the left control press should be sent at each interval. (Default was I believe 2 minutes) 

If the window has activity within the last minute it is skipped till the next interval. 

Some controllers appear to have caused some people issues and older releases have had some bugs.

**Comment by Rykimaruh** [comment]
I installed the plugin through Dalamud

**Comment by Eternita-S** [comment]
Dalamud plugin reads afk timer from the game and sends keypress once it has reached 2 minutes. If it doesn't works, then please go to any solo dungeon, type `/xllog`, set click on "options", set log level to "verbose", wait afk 10 minutes until you get kicked from the dungeon for inactivity and attach your `%appdata%\XIVLauncher\dalamud.log` to the message

**Comment by Eternita-S** [comment]
> my character doesn't seem to move (I am assuming that the character moves on its own).

No, it actually won't move

**Comment by Rykimaruh** [comment]
It seems to be working as I could see the signal being sent in the log and I left my character for a long period of time and have not been kicked.

Here's the log just in case.
[dalamud.log](https://github.com/Eternita-S/AntiAfkKick/files/7721991/dalamud.log)
 
Thank you for your time!
