### ISSUE TITLE
Windows Defender detection

### ISSUE THREAD

**Issue by Necroxys77** [Eternita-S/AntiAfkKick#12]
Hi,
just for acknowledgement, Windows Defender is starting to flag it as PUA.

![image](https://user-images.githubusercontent.com/17526371/146640387-c8feac3a-3f23-4c2c-870b-1e8a9f09bdf4.png)

**Comment by Eternita-S** [comment]
Add exception to windows defender like described in article: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by Necroxys77** [comment]
Yeah I know that :)
As I said, this is just for acknowledgement since Defender signatures have been updated
