### ISSUE TITLE
Windows Defender keeps putting the program in quarantine.

### ISSUE THREAD

**Issue by Geodad478** [Eternita-S/AntiAfkKick#13]
I really only use my Windows computer for Final Fantasy XIV, so I'm not very knowledgeable about how to fix this or if it can be fixed.

**Comment by patrat46** [comment]
You can add an exclusion to windows defender. 

https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

When programming programs it's hard to not raise a few virus flags.

**Comment by rrbailey89** [comment]
its coming up as a trojan: https://www.virustotal.com/gui/file/924db9b073d3b1c873472236928aee7441f05d7ff8eabc5e8f608597754e9f85/detection

**Comment by Eternita-S** [comment]
Please contact your antivirus manufactorer and report false positive.
In meantime you can add program to antivirus exception list. Please refer to your antivirus documentation for details on how to do it.
