### ISSUE TITLE
Standalone Error

### ISSUE THREAD

**Issue by perishoot** [Eternita-S/AntiAfkKick#14]
Not sure what we're doing wrong here, but attempting to run the standalone version results in the "side-by-side configuration is incorrect" error message upon launch. My buddy tried it as well and said he couldn't get it to run either. Thoughts or ideas as to what we're missing?

**Comment by Eternita-S** [comment]
Please make sure that you have:
- Visual studio runtimes all installed, you can download here: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/ (extract, run install_all.bat as admininstrator)
- .NET framework 4.8 installed, you can download it here: https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0

**Comment by perishoot** [comment]
Afraid the issue wasn't resolved. I updated my runtimes again just to be sure even though I just did it a couple of weeks ago. Thanks for trying to troubleshoot.

**Comment by Eternita-S** [comment]
Unfortunately I don't really know the root of the issue and I'm not sure how to diagnose it either. It seems that generally this problem is due to corrupted visual c++ resists or .net framework, but it also can be caused by some other system issues. Can you instead use either ACT or Dalamud plugin?

**Comment by perishoot** [comment]
It's all good! Just thought I'd give it a try and see if it'd spare me from having to manually run macros, but it's not a huge loss. Cheers for trying to help me out, and thanks for making up the content regardless.
