### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by Haychii90** [Eternita-S/AntiAfkKick#15]
The plugin doesn't seem to be working anymore.

**Comment by Eternita-S** [comment]
which of them?

**Comment by Haychii90** [comment]
The dalamud one. I relaunched the game and reinstalled the plugin and it’s working again, never had this happen before though.

**Comment by Eternita-S** [comment]
Please do the following:
- type `/xllog`
- press cog icon
- set log level to "debug"

If this happens again, send me your `%appdata%\XIVLauncher\dalamud.log` file so I can identify the issue

**Comment by Eternita-S** [comment]
If it still doesn't works, please reopen the issue and attach the log
