### ISSUE TITLE
Is there any way of knowing if the standalone version is working as intended?

### ISSUE THREAD

**Issue by Rykimaruh** [Eternita-S/AntiAfkKick#17]
Hi, just as the title says.

**Comment by Eternita-S** [comment]
to test it without risk of being kicked - enter any duty undersized and go afk for 10 minutes. Should you come back and see no messages that you are being inactive - the program/plugin is working fine. Should you see a warning about auto-kick from duty, it means anti-kick does not works.

**Comment by Rykimaruh** [comment]
yup, it works! thanks!
