### ISSUE TITLE
Not a problem but a thank you

### ISSUE THREAD

**Issue by Jibby2121** [Eternita-S/AntiAfkKick#18]
Cant thank you on discord cause privacy settings so I hope you dont mind me saying this here Just wanted to say thanks for the afk plugin. I for one appreciate it and don't abuse it like overnighting with it. I use it when I work so I don't get kicked when I'm on a work call or something. 

Im sure some people come at you with pitchforks over this plugin but from myself and many others IM sure I am grateful for the plugin.

Have a great day and happy new year and Ill continue to support this.

**Comment by Eternita-S** [comment]
Thank you for review, and happy new year too!
If you are on xivlauncher's or act's discord, you should be able to DM me if you yourself have DMs enabled on either of these servers.
Actually nobody complained about it or almost nobody, though I don't really advertise plugin anyhow, it's just here for whoever finds it, and people who are searching things like that are usually searching them not to complain :)
