### ISSUE TITLE
ACT Anti-AFK no long appears to work

### ISSUE THREAD

**Issue by azeda** [Eternita-S/AntiAfkKick#20]
I have the plugin installed via ACT, and it has worked flawlessly until today. I was logged out of the game while addon was running.

**Comment by Eternita-S** [comment]
do you remember if your game was focused or if you were alt-tabbed to other window?

**Comment by azeda** [comment]
I believe the game was in focus. However, I have had the game out of focus before for extended periods of time and had no change in status in game.

**Comment by azeda** [comment]
I do not
