### ISSUE TITLE
Standalone executable disappearing after download with no rime nor reason

### ISSUE THREAD

**Issue by firedrake150** [Eternita-S/AntiAfkKick#22]
For me, the .dll works just fine, but I wanted to have the standalone for a backup variant.  My antivirus isn't flagging it, it's just disappearing immediately after download on Win 11.  No warnings or anything, it's just, gone.

**Comment by patrat46** [comment]
Check your antivirus settings. 
I think in windows security the "Reputation-Based Protection" can block the download. Its located in Windows Security > App & Network protection.
