### ISSUE TITLE
Safe to use plugin?

### ISSUE THREAD

**Issue by TheCynicalSoul** [Eternita-S/AntiAfkKick#25]
Just wondering is people are getting banned from using this as I've heard people had gotten banned for using macros before. If it's unlikely then that would be cool to avoid the que times.

**Comment by Eternita-S** [comment]
People aren't getting banned even for obvious things like botting 24/7 many years straight and for quadruple-weave cheating. And avoiding afk kick isn't even detectable by server.
Of course if you will make it obvious that you're using the plugin like leaving your char for a week afking in limsa, there could be consequences, even then - very unlikely
