### ISSUE TITLE
AntiAFGKick

### ISSUE THREAD

**Issue by Latenja** [Eternita-S/AntiAfkKick#26]
FF14 had a huge new patch today and the AntiAFGKick Standalone no longer works. :(

**Comment by Spanglish1337** [comment]
> Hello! It should work. Please check if you maybe have this issue #16 If you are starting game (or steam if you're using steam) as admin, you need to start program as admin too

Sorry to hijack this post! Just wanted to inform that someone tried the testing branch of Dalamud and the Anti AFK kick addon mentions is incompatible at the moment.

![image](https://user-images.githubusercontent.com/89648547/163419364-22604153-8754-4f91-9fee-a2b7af1ecb53.png)
