### ISSUE TITLE
No longer working as of 12/09/21?

### ISSUE THREAD

**Issue by Miz-Tifa** [Eternita-S/AntiAfkKick#8]
I had used this over the past few days via ACT with no issue (currently caring for family with limited mobility, and have to step away frequently).  However, as of today the activity in the plugin window appeared different, and I had gotten kicked back to the title screen.  

![image](https://user-images.githubusercontent.com/95900657/145522731-48512b83-b9c8-4251-bdb8-08850d69272f.png)

**Comment by Eternita-S** [comment]
Hello!
This looks like outdated version of a plugin. Please update it: https://github.com/Eternita-S/AntiAfkKick/releases/tag/2.0.0.0

**Comment by Miz-Tifa** [comment]
> Hello! This looks like outdated version of a plugin. Please update it: https://github.com/Eternita-S/AntiAfkKick/releases/tag/2.0.0.0

First off, thank you so much for the fast reply! I'm admittedly new to GitHub's UI, and didn't realize there was an update because I was only looking at the original release date that was showing 18 days ago. :'D  My ignorance aside, the update works perfectly.  Appreciate that you took the time to create, update and share this!
